// FIX: Same as other route files — Supabase and dotenv should not be set up here.
// Import from config/supabase.js instead.
import 'dotenv/config';
const express = require('express');
// FIX: jsonwebtoken is imported but never used in this file.
const jsonwebtoken = require('jsonwebtoken');
// FIX: A local 'app' instance is created here, but it is never exported or mounted in index.js.
// Every route below that uses 'app.get/post/patch' is registered on this local dead-end app —
// those routes will never be reachable. Change all 'app.' calls to 'router.'
const app = express();
const port = 8000;
const { createClient } = require("@supabase/supabase-js");
const supabaseUrl = process.env.DATABASE_URL;
// FIX: SUPABASE_PUBLISHABLE_DEFAULT_KEY is not a declared variable — server will crash on startup.
// Change to: process.env.SUPABASE_KEY
const supabaseKey = SUPABASE_PUBLISHABLE_DEFAULT_KEY;
const supabase = createClient(supabaseUrl, supabaseKey);
const router = express.Router();

// FIX: app.post — should be router.post (see note above about local 'app' instance)
// FIX: No error handling — if the insert fails, the endpoint still responds 200 with null data.
// Add: if (error) return res.status(500).json({ error: error.message })
//Add teacher, ADMIN
app.post('/admin/teachers', async (req, res) => {
  const { data, error } = await supabase
    .from('teachers')
    .insert({
      // FIX: 'id', 'created_at', and 'updated_at' should not come from the client.
      // The database generates these automatically. Letting clients set 'id' can cause conflicts.
      'id': req.body.id,
      'name': req.body.name,
      'email': req.body.email,
      'phone_number': req.body.phone_number,
      'created_at': req.body.created_at,
      'updated_at': req.body.updated_at});
  res.send(data);
});

// FIX: app.get — should be router.get
// FIX: No error handling.
//TBA: Parent info + fix programs
//All students with program + parent info, ADMIN
app.get('/admin/students', async (req, res) => {
  const { data, error } = await supabase
    .from('students')
    // FIX: This select query is not valid Supabase syntax. 'programs ()' and 'users ()' are not
    // how you join related tables. Use the Supabase join format: '*, registrations(*, programs(*))'
    .select('students, programs (), users ()') // Retrieve program, parent, and student information with a student id that matches request body
  res.send(data);
});

// FIX: app.post — should be router.post
// FIX: No error handling.
//Create program, ADMIN
app.post('/admin/programs', async (req, res) => {
  const { data, error } = await supabase
    .from('programs')
    .insert({
      // FIX: 'id' should not come from the client — the database generates it automatically.
      'id': req.body.id,
      'name': req.body.name,
      // FIX: Copy-paste mistake — 'level' is reading from req.body.email instead of req.body.level.
      'level': req.body.email,
      // FIX: Copy-paste mistake — 'target_age' is reading from req.body.phone_number instead of req.body.target_age.
      'target_age': req.body.phone_number,
      // FIX: Copy-paste mistake — 'description' is reading from req.body.created_at instead of req.body.description.
      'description': req.body.created_at,
      'prerequisites': req.body.prerequisites,
      'status': req.body.status,
      // FIX: created_at and updated_at are auto-generated by the database. Don't set them from the client.
      'created_at': req.body.created_at,
      'updated_at': req.body.updated_at});
  res.send(data);
});

// FIX: app.get — should be router.get
// FIX: No error handling.
//Program detail with slot counts ADMIN
app.get('/admin/programs/:id', async (req, res) => {
  const { data: { user } } = await supabase.auth.getUser();
  // FIX: This is an admin endpoint, but the role check says 'parent'. It's backwards.
  // A parent will pass this check and get admin data; an admin will be blocked.
  // Change 'parent' to 'admin'. Better yet, move this check to middleware so it's not
  // scattered and repeated across every route.
  if (data.user.role == 'parent') {
    const { data, error } = await supabase
      .from('programs')
      .select()
      .eq('id', req.params.id); // Retrieve program information with an id that matches request body
    // FIX: 'max_capacity' and 'current_count' are not variables in this scope.
    // They exist inside each row of the query result (e.g., data[0].max_capacity).
    // This line will throw "ReferenceError: max_capacity is not defined".
    data.slotcount = (max_capacity - current_count) // Set slotcount property to the max capacity of the program - current registrations
    res.send(data);
  }
});

// FIX: app.get — should be router.get
// FIX: No error handling. Also missing joins to return student and time slot details with each registration.
//Pending registrations queue, ADMIN
app.get('/admin/registrations', async (req, res) => {
  const { data, error } = await supabase
    .from('registrations')
    .select()
    .eq('status', 'pending'); // Retrieve all registrations still marked pending
  res.send(data);
});

// FIX: app.patch — should be router.patch
// FIX: No error handling.
// FIX: When a registration is rejected, current_count on time_slots should be decremented.
// This endpoint only updates the status but never adjusts the slot count, which will leave
// the slot showing as more full than it actually is.
//Approve or reject a registration, ADMIN
app.patch('/admin/registrations/:id', async (req, res) => {
  const { data, error } = await supabase
    .from('registrations')
    .update( {'status': req.body.status} )
    .eq('id', req.params.id); // Patch a registration matching the given ID
  res.send(data);
});

// FIX: app.post — should be router.post
// FIX: No error handling.
//Create time slot, ADMIN
app.post('/admin/time-slots', async (req, res) => {
  const { data: { user } } = await supabase.auth.getUser();
  // FIX: Same backwards role check as /admin/programs/:id above — says 'parent' but should be 'admin'.
  if (data.user.role == 'parent') {
    const { data, error } = await supabase
      // FIX: Wrong table name. This inserts into 'programs' instead of 'time_slots'.
      // Every new time slot created via this endpoint is being silently written to the wrong table.
      .from('programs')
      .insert({
        // FIX: 'id', 'current_count', 'created_at', 'updated_at' should not come from the client.
        // 'id' is auto-generated. 'current_count' starts at 0 by default.
        'id': req.body.id,
        'program_id': req.body.program_id,
        'teacher_id': req.body.teacher_id,
        'location_id': req.body.location_id,
        'mode': req.body.mode,
        'day_of_week': req.body.day_of_week,
        'start_time': req.body.start_time,
        'end_time': req.body.end_time,
        'max_capacity': req.body.max_capacity,
        'current_count': req.body.current_count,
        'created_at': req.body.created_at,
        'updated_at': req.body.updated_at});
    res.send(data);
    }
});

module.exports = router; //Export routes
