// FIX: Same as other route files — Supabase and dotenv should not be set up here.
// Import from config/supabase.js instead. dotenv only needs to run once in index.js.
import 'dotenv/config';
const express = require('express');
// FIX: jsonwebtoken is imported but never used in this file.
const jsonwebtoken = require('jsonwebtoken');
// FIX: app, port, and router are created here but 'app' is a local copy — it is not
// the same app that's running in index.js. Routes registered on this local 'app'
// will never be reachable. All routes must use 'router' instead.
const app = express();
const port = 8000;
const { createClient } = require("@supabase/supabase-js");
const supabaseUrl = process.env.DATABASE_URL;
// FIX: SUPABASE_PUBLISHABLE_DEFAULT_KEY is not a declared variable — server will crash on startup.
// Change to: process.env.SUPABASE_KEY
const supabaseKey = SUPABASE_PUBLISHABLE_DEFAULT_KEY;
const supabase = createClient(supabaseUrl, supabaseKey);
const router = express.Router();

// FIX: This router is mounted at '/registrations' in index.js, so this route's full URL
// would become '/registrations/registrations/my' — which is doubled and wrong.
// Change '/registrations/my' to just '/my'.
router.get('/registrations/my', async (req, res) => {
  const { data, error } = await supabase
    .from('registrations')
    .select()
    .eq('student_id', req.body.student_id); // Retrieve registration information with a student id that matches request body
  res.send(data);
});

// FIX: app.post() registers this route on the local 'app' instance, not on 'router'.
// Since 'router' is what gets exported and mounted in index.js, this route will never be reachable.
// Change app.post to router.post.
// FIX: No error handling — if supabase returns an error, the endpoint still responds with
// empty data and a 200 OK, making it look like the insert succeeded when it didn't.
app.post('/registrations', async (req, res) => {
  // FIX: The destructured variable is named 'user' (from { data: { user } }),
  // but the role check below uses 'data.user.role'. 'data' is not defined here — this will crash.
  // Change to: user.role == 'parent'
  const { data: { user } } = await supabase.auth.getUser();
  if (data.user.role == 'parent') {
    const { data, error } = await supabase
      .from('registrations')
      .insert({
        // FIX: 'id' should not come from the client — the database generates it automatically.
        'id': req.body.id,
        'student_id': req.body.student_id,
        'program_id': req.body.program_id,
        'time_slot_id': req.body.time_slot_id,
        // FIX: 'status', 'submitted_at', 'reviewed_at', and 'reviewed_by' should never be
        // set by the client. 'status' defaults to 'pending' in the DB. 'reviewed_*' fields
        // are for admin use only. Letting clients set these allows anyone to approve their own
        // registration or fake review data.
        'status': req.body.status,
        'submitted_at': req.body.submitted_at,
        'reviewed_at': req.body.reviewed_at,
        'reviewed_by': req.body.reviewed_by,
        // FIX: created_at and updated_at are auto-generated by the database. Don't set them from the client.
        'created_at': req.body.created_at,
        'updated_at': req.body.updated_at});
    res.send(data);
  }
});

module.exports = router; //Export routes
